include("utils.jl")
include("earthquick_main.jl")

disp, state, v_bd = simulate()
init(sess)
DISP, STATE, VEL = run(sess, [disp,state, v_bd]);
# DISP

# figure()
# plot(time[eq_ind], v[1, eq_ind])
# plot(time[eq_ind], VEL[:,1])
# figure()
# plot(time[eq_ind], psi[1, eq_ind])
# plot(time[eq_ind], STATE[:,1], "o--")
# figure()
# plot(time[eq_ind], bd_left[1, eq_ind])
# plot(time[eq_ind], DISP[:,1], "--")

close("all")
figure()
subplot(311)
plot(t, VEL[1:end-1,1])
subplot(312)
plot(t, STATE[1:end-1,1], "--")
subplot(313)
plot(t, DISP[1:end-1,1], "--")
suptitle("Ours")

figure()
subplot(311)
plot(time[eq_ind].-time[eq_ind[1]], v[1, eq_ind])
subplot(312)
plot(time[eq_ind].-time[eq_ind[1]], psi[1, eq_ind])
subplot(313)
plot(time[eq_ind].-time[eq_ind[1]], bd_left[1, eq_ind])
suptitle("Referece")