language: julia
dist: xenial
python:
  - "3.7"
git:
  depth: 3
  quiet: true
julia:
  - 1.3
  - 1.4
  - 1.5
os:
  - osx
  - linux
  - windows
script:
  - julia --color=yes -e 'using Pkg;  Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("AdFem")'
notifications:
  email: false