language: julia
dist: xenial
python:
  - "3.7"
git:
  depth: 3
  quiet: true
julia:
  - 1.3
  - 1.4
  - 1.5
os:
  - osx
  - linux
  - windows
script:
 - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/kailaix/ADCME.jl", rev="master")); Pkg.build("ADCME")'
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';